default: &default
  access_key_id:     'xxx'
  secret_access_key: 'xxx'
  region:            'eu-central-1'

development:
  <<: *default
  bucket: ohoronka-dev

test:
  <<: *default
  bucket: ohoronka-test

production:
  <<: *default
  bucket: ohoronka
