default: &default
  cache: &cache
    host: localhost
    port: 6379
    db: 0
    namespace: cache
  sidekiq: &sidekiq
    host: localhost
    port: 6379
    db: 13
    namespace: cache

development:
  <<: *default
  cache:
    <<: *cache
    db: 11

test:
  <<: *default
  cache:
    <<: *cache
    db: 12

production:
  <<: *default
  cache:
    <<: *cache
    db: 10